// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "C:\Users\wonit\Documents\Arduino\libraries\lvgl\lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Spinbox1;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Container12;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui____initial_actions0;



LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_Font16);
LV_FONT_DECLARE(ui_font_Font30);
LV_FONT_DECLARE(ui_font_Font50);
LV_FONT_DECLARE(ui_font_Font70);
LV_FONT_DECLARE(ui_font_Font25);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
